### ISSUE TITLE
how to get the audio stream about caller or responder on a call

### ISSUE THREAD

**Issue by hexianbin1994** [isabyr/pjsipstreamer#4]
Firstly , thanks a lot for the project, it can get the audio stream on a call, it helps a lot.

Now ,I have a question about how to get the one side audio stream.
For example , by demo.py, I use sip:1001 makecall sip:1002, the AudioMediaCapture will records 1001's audio and 1002's audio together,the audio is mixed. how to only get 1002's audio stream, like wireshark.

**Comment by isabyr** [comment]
Hi,

You mean if you record the call? In the example provided I use MixMonitor it should write either in separate files, or in single file with separate channels. Did you check the recording?

**Comment by hexianbin1994** [comment]
Actually , I only build docker container as ./pjsip/Dockerfile.pjsip , it have not set the asterisk config, did I need to set the asterisk config as ./asterisk_files?

I get the recorder by ./pjsip/pjsuademo/demo.py, like :
```py
    f = open('output.lpcm', 'wb')
    f2 = open('hw.raw', 'rb')
    hwraw = f2.read()
    n = 320
    [call.putFrame(hwraw[i:i+320]) for i in range(0, len(hwraw), n)]

    for i in range(10):
        time.sleep(1)
        data = call.getFrames()
        if data:
            f.write(data)
    f.close()
```

then I turn the ./output.lpcm to wav file, it records the caller and answerer audio. but I only want to get the answerer, it can set some parameters to do it ?

**Comment by isabyr** [comment]
Ok, let me check it

**Comment by isabyr** [comment]
can you send me your output.lpcm file?

**Comment by hexianbin1994** [comment]
OK， output.lpcm is in here. 

[output.zip](https://github.com/isabyr/pjsipstreamer/files/12911458/output.zip)

**Comment by isabyr** [comment]
sounds like an echo from speakers

**Comment by hexianbin1994** [comment]
no, sounds 0-1 second like speak "hello world" is the player sound,  in demo.py  【f2 = open('hw.raw', 'rb')】;  2 second and later,   I speak "hello hello" and record. 
so the output.lpcm file records speaker and answerer audio together.

**Comment by isabyr** [comment]
the playback of "hello world" is too quiet, looks like your sip:1002's mic is capturing the sound from the speakers and echoing back to sip:1001

**Comment by hexianbin1994** [comment]
ok,you are right, I use another hardware equipment and  resolve this problem,thanks~

**Comment by cumthxy** [comment]
> ok,you are right, I use another hardware equipment and resolve this problem,thanks~

i get the same error .how do you solve it?
